// Code generated by protoc-gen-go.
// source: pmessage.proto
// DO NOT EDIT!

/*
Package envoyds is a generated protocol buffer package.

It is generated from these files:
	pmessage.proto

It has these top-level messages:
	ServiceGetResponse
	ServicePostRequest
	ServiceUpdateLoadBalancingRequest
	Host
	Tags
*/
package envoyds

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceGetResponse struct {
	Env     string  `protobuf:"bytes,1,opt,name=env" json:"env,omitempty"`
	Hosts   []*Host `protobuf:"bytes,2,rep,name=hosts" json:"hosts,omitempty"`
	Service string  `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
}

func (m *ServiceGetResponse) Reset()                    { *m = ServiceGetResponse{} }
func (m *ServiceGetResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceGetResponse) ProtoMessage()               {}
func (*ServiceGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceGetResponse) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ServiceGetResponse) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *ServiceGetResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type ServicePostRequest struct {
	Ip              string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	ServiceRepoName string `protobuf:"bytes,2,opt,name=service_repo_name,json=serviceRepoName" json:"service_repo_name,omitempty"`
	Port            int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Revision        string `protobuf:"bytes,4,opt,name=revision" json:"revision,omitempty"`
	Tags            *Tags  `protobuf:"bytes,5,opt,name=tags" json:"tags,omitempty"`
}

func (m *ServicePostRequest) Reset()                    { *m = ServicePostRequest{} }
func (m *ServicePostRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicePostRequest) ProtoMessage()               {}
func (*ServicePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServicePostRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServicePostRequest) GetServiceRepoName() string {
	if m != nil {
		return m.ServiceRepoName
	}
	return ""
}

func (m *ServicePostRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServicePostRequest) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ServicePostRequest) GetTags() *Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ServiceUpdateLoadBalancingRequest struct {
	LoadBalancingWeight int32 `protobuf:"varint,1,opt,name=load_balancing_weight,json=loadBalancingWeight" json:"load_balancing_weight,omitempty"`
}

func (m *ServiceUpdateLoadBalancingRequest) Reset()         { *m = ServiceUpdateLoadBalancingRequest{} }
func (m *ServiceUpdateLoadBalancingRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceUpdateLoadBalancingRequest) ProtoMessage()    {}
func (*ServiceUpdateLoadBalancingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *ServiceUpdateLoadBalancingRequest) GetLoadBalancingWeight() int32 {
	if m != nil {
		return m.LoadBalancingWeight
	}
	return 0
}

type Host struct {
	IpAddress       string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	LastCheckIn     string `protobuf:"bytes,2,opt,name=last_check_in,json=lastCheckIn" json:"last_check_in,omitempty"`
	Port            int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Revision        string `protobuf:"bytes,4,opt,name=revision" json:"revision,omitempty"`
	Service         string `protobuf:"bytes,5,opt,name=service" json:"service,omitempty"`
	ServiceRepoName string `protobuf:"bytes,6,opt,name=service_repo_name,json=serviceRepoName" json:"service_repo_name,omitempty"`
	Tags            *Tags  `protobuf:"bytes,7,opt,name=tags" json:"tags,omitempty"`
}

func (m *Host) Reset()                    { *m = Host{} }
func (m *Host) String() string            { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()               {}
func (*Host) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Host) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Host) GetLastCheckIn() string {
	if m != nil {
		return m.LastCheckIn
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Host) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *Host) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Host) GetServiceRepoName() string {
	if m != nil {
		return m.ServiceRepoName
	}
	return ""
}

func (m *Host) GetTags() *Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tags struct {
	Az                  string `protobuf:"bytes,1,opt,name=az" json:"az,omitempty"`
	Region              string `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	InstanceId          string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Canary              bool   `protobuf:"varint,4,opt,name=canary" json:"canary,omitempty"`
	LoadBalancingWeight int32  `protobuf:"varint,5,opt,name=load_balancing_weight,json=loadBalancingWeight" json:"load_balancing_weight,omitempty"`
}

func (m *Tags) Reset()                    { *m = Tags{} }
func (m *Tags) String() string            { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()               {}
func (*Tags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Tags) GetAz() string {
	if m != nil {
		return m.Az
	}
	return ""
}

func (m *Tags) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Tags) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Tags) GetCanary() bool {
	if m != nil {
		return m.Canary
	}
	return false
}

func (m *Tags) GetLoadBalancingWeight() int32 {
	if m != nil {
		return m.LoadBalancingWeight
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceGetResponse)(nil), "envoyds.ServiceGetResponse")
	proto.RegisterType((*ServicePostRequest)(nil), "envoyds.ServicePostRequest")
	proto.RegisterType((*ServiceUpdateLoadBalancingRequest)(nil), "envoyds.ServiceUpdateLoadBalancingRequest")
	proto.RegisterType((*Host)(nil), "envoyds.Host")
	proto.RegisterType((*Tags)(nil), "envoyds.Tags")
}

func init() { proto.RegisterFile("pmessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xd5, 0x26, 0xbb, 0x49, 0x3b, 0x51, 0x0b, 0x18, 0x81, 0x56, 0x48, 0x88, 0x74, 0xb9, 0x54,
	0x1c, 0x72, 0x28, 0x5f, 0x00, 0x1c, 0xa0, 0x12, 0x42, 0x68, 0x01, 0xf5, 0x68, 0x4d, 0xd7, 0xa3,
	0x8d, 0x45, 0x62, 0x1b, 0x8f, 0x09, 0x6a, 0x7f, 0x85, 0x23, 0x7f, 0xc6, 0x97, 0x20, 0x7b, 0xbd,
	0x55, 0x2b, 0x35, 0x07, 0x6e, 0x7e, 0xf3, 0xf4, 0xec, 0x79, 0xef, 0x19, 0x8e, 0xdd, 0x96, 0x98,
	0xb1, 0xa7, 0x95, 0xf3, 0x36, 0x58, 0x31, 0x27, 0xb3, 0xb3, 0x57, 0x8a, 0x1b, 0x02, 0xf1, 0x85,
	0xfc, 0x4e, 0x77, 0xf4, 0x9e, 0x42, 0x4b, 0xec, 0xac, 0x61, 0x12, 0x0f, 0x61, 0x4a, 0x66, 0x57,
	0x17, 0xcb, 0xe2, 0xf4, 0xb0, 0x8d, 0x47, 0xf1, 0x12, 0xaa, 0xb5, 0xe5, 0xc0, 0xf5, 0x64, 0x39,
	0x3d, 0x5d, 0x9c, 0x1d, 0xad, 0xf2, 0x05, 0xab, 0x0f, 0x96, 0x43, 0x3b, 0x70, 0xa2, 0x86, 0x39,
	0x0f, 0x97, 0xd5, 0xd3, 0x24, 0x1d, 0x61, 0xf3, 0xa7, 0xb8, 0x79, 0xe7, 0x73, 0x14, 0xd0, 0x8f,
	0x9f, 0xc4, 0x41, 0x1c, 0xc3, 0x44, 0xbb, 0xfc, 0xcc, 0x44, 0x3b, 0xf1, 0x0a, 0x1e, 0x65, 0x85,
	0xf4, 0xe4, 0xac, 0x34, 0xb8, 0xa5, 0x7a, 0x92, 0xe8, 0x07, 0x99, 0x68, 0xc9, 0xd9, 0x4f, 0xb8,
	0x25, 0x21, 0xa0, 0x74, 0xd6, 0x87, 0xf4, 0x52, 0xd5, 0xa6, 0xb3, 0x78, 0x06, 0x07, 0x9e, 0x76,
	0x9a, 0xb5, 0x35, 0x75, 0x99, 0x64, 0x37, 0x58, 0x9c, 0x40, 0x19, 0xb0, 0xe7, 0xba, 0x5a, 0x16,
	0x77, 0x0c, 0x7c, 0xc5, 0x9e, 0xdb, 0x44, 0x35, 0x17, 0x70, 0x92, 0x97, 0xfc, 0xe6, 0x14, 0x06,
	0xfa, 0x68, 0x51, 0xbd, 0xc5, 0x0d, 0x9a, 0x4e, 0x9b, 0x7e, 0xdc, 0xf9, 0x0c, 0x9e, 0x6c, 0x2c,
	0x2a, 0x79, 0x39, 0x12, 0xf2, 0x17, 0xe9, 0x7e, 0x1d, 0x92, 0x8d, 0xaa, 0x7d, 0xbc, 0xb9, 0x2d,
	0xba, 0x48, 0x54, 0xf3, 0xb7, 0x80, 0x32, 0x06, 0x25, 0x9e, 0x03, 0x68, 0x27, 0x51, 0x29, 0x4f,
	0xcc, 0xd9, 0xf8, 0xa1, 0x76, 0x6f, 0x86, 0x81, 0x68, 0xe0, 0x68, 0x83, 0x1c, 0x64, 0xb7, 0xa6,
	0xee, 0xbb, 0xd4, 0x26, 0x7b, 0x5f, 0xc4, 0xe1, 0xbb, 0x38, 0x3b, 0x37, 0xff, 0xed, 0xfb, 0x56,
	0x29, 0xd5, 0x9d, 0x52, 0xee, 0x4f, 0x7b, 0x76, 0x7f, 0xda, 0x63, 0x7a, 0xf3, 0xfd, 0xe9, 0xfd,
	0x2e, 0xa0, 0x8c, 0x30, 0xb6, 0x8a, 0xd7, 0x63, 0xab, 0x78, 0x2d, 0x9e, 0xc2, 0xcc, 0x53, 0x1f,
	0x77, 0x1b, 0xec, 0x64, 0x24, 0x5e, 0xc0, 0x42, 0x1b, 0x0e, 0x68, 0x3a, 0x92, 0x5a, 0xe5, 0x2f,
	0x03, 0xe3, 0xe8, 0x5c, 0x45, 0x61, 0x87, 0x06, 0xfd, 0x55, 0x32, 0x75, 0xd0, 0x66, 0xb4, 0xbf,
	0x82, 0x6a, 0x6f, 0x05, 0x97, 0xb3, 0xf4, 0xf1, 0x5f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x34,
	0xb4, 0x03, 0xf7, 0x0a, 0x03, 0x00, 0x00,
}
